### ISSUE TITLE
The structure of the dataset

### ISSUE THREAD

**Issue by yyf17** [tianrun-chen/SAM-Adapter-PyTorch#10]
Very wonderful work! Can you provide the structure of the dataset?

**Comment by tianrun-chen** [comment]
The setup is straightforward - there is a folder for masks that contains the mask files, and another folder for images that stores the corresponding RGB images (it is important to verify the file names in the dataloader prior to training). The matching of masks and RGB images is based on their shared file names, which are usually numbered from 1 to N, where N represents the total number of images.

**Comment by AnnemSony** [comment]
i changed the path to my desired datasets, still getting the error  
  File "/isilon/datalake/cialab/scratch/cialab/sony/SAMA/datasets/image_folder.py", line 42, in __init__
    filenames = sorted(os.listdir(path))
FileNotFoundError: [Errno 2] No such file or directory: '/public2/home/chaotao/datasets/codDataset/train/img'
