### ISSUE TITLE
visualize the predicted mask

### ISSUE THREAD

**Issue by xypu98** [tianrun-chen/SAM-Adapter-PyTorch#18]
Hello, are there some code or scripts to achieve the visualization of predicted masks and save the mask picture? Thanks a lot!

**Comment by Maxcharm** [comment]
Have you solved the problem yet? For me I just stored the binary prediction mask and visualize it with opencv. It is pretty trivial.

**Comment by tianrun-chen** [comment]
Just like @Maxcharm mentioned, one option is to store the binary prediction mask and visualize it using OpenCV.

**Comment by AnnemSony** [comment]
> Have you solved the problem yet? For me I just stored the binary prediction mask and visualize it with opencv. It is pretty trivial.

have you solved the problem

**Comment by Linn0910** [comment]
> Have you solved the problem yet? For me I just stored the binary prediction mask and visualize it with opencv. It is pretty trivial.

hello！Could you please provide any details about the visualize?I'm really need this and appreciate for your reply!
