### ISSUE TITLE
关于SAM原文的分割结果

### ISSUE THREAD

**Issue by lwpyh** [tianrun-chen/SAM-Adapter-PyTorch#21]
您好

感谢分享这篇工作，想请教一下对比的SAM baseline的分割结果是如何获得的呢？在另一个issue里面似乎您提及了通过使用覆盖全图的bbox作为prompt,那除了这个bbox以外是否使用everything模式或者某个点作为prompt进行提示呢？

期待您的回复

**Comment by tianrun-chen** [comment]
Hello, we have employed various prompting methods in our approach. For the quantitative analysis, we utilized bounding boxes that encompass the entire image. In the qualitative results, we used both bounding boxes and the "everything" mode. It is worth noting that using points as prompts would require manual intervention and represents a different problem setting. Nevertheless, we encourage you to investigate this approach if it aligns with your research interests :D
