### ISSUE TITLE
What is the sub-folder `mmseg` used for?

### ISSUE THREAD

**Issue by jinx2018** [tianrun-chen/SAM-Adapter-PyTorch#22]
What is the subfolder [`mmseg`](https://github.com/tianrun-chen/SAM-Adapter-PyTorch/tree/main/models#:~:text=..-,mmseg,-(Directory)) used for ?

And it has a different implementation of the SAM training.

**Comment by huoyiru** [comment]
Hello, I have the same question about this, did you solve your question?

**Comment by jinx2018** [comment]
> Hello, I have the same question about this, did you solve your question?

The subfolder provided the `ImageEncoderViT, MaskDecoder, TwoWayTransformer` models.

**Comment by huoyiru** [comment]
Thank you for your answer, do you know what prompt_encoder.py does? Did you try to call it during training?

**Comment by jinx2018** [comment]
> Thank you for your answer, do you know what prompt_encoder.py does? Did you try to call it during training?

It seem that the `prompt_encoder.py`  is the original prompt encoder design from  the SAM paper. If you try to train the Adapter-SAM, then this file won't be used.
