### ISSUE TITLE
F input for adapter

### ISSUE THREAD

**Issue by nikky4D** [tianrun-chen/SAM-Adapter-PyTorch#25]
Can you show me the code where the F input is created for input to the adapter?

**Comment by Drchip61** [comment]
<img width="550" alt="image" src="https://github.com/tianrun-chen/SAM-Adapter-PyTorch/assets/75516995/e8c1f904-86ab-472d-87ec-30fb3f141a5b">
I find the code, but i cannot reach the performance the author write!

**Comment by tianrun-chen** [comment]
Have you tried the pretrained code to test the performance?
