### ISSUE TITLE
instance segmentation

### ISSUE THREAD

**Issue by shuyansy** [tianrun-chen/SAM-Adapter-PyTorch#29]
can this model suit the instance segmentation？ For example， for one image， there are multiple masks.

**Comment by thangngoc89** [comment]
I came here to ask the same question :)

**Comment by Hannahzyt** [comment]
same question

**Comment by tianrun-chen** [comment]
Currently the model is unable to do that. We are working on that. You are also welcomed to check recent open vocabulary image segmentation task.

**Comment by 1244632315** [comment]
> Currently the model is unable to do that. We are working on that. You are also welcomed to check recent open vocabulary image segmentation task.

how about the progress now?
