### ISSUE TITLE
Freeze encoder

### ISSUE THREAD

**Issue by zkyseu** [tianrun-chen/SAM-Adapter-PyTorch#31]
Hi, thanks for your wonderful work! I have a question that SAM-adapter freezes the image encoder which is described in the paper. But I see that although the freeze code is provided, they are not runned. Whether is it necessary to freeze image encoder. Thanks!

**Comment by tianrun-chen** [comment]
As we mentioned in our manuscript, our approach involves an adaptation method that eliminates the need for lengthy fine-tuning.  It's possible to fine-tune the SAM on your specific task without freezing the image encoder and also utilize the adapters' input.

**Comment by cillayue** [comment]
> As we mentioned in our manuscript, our approach involves an adaptation method that eliminates the need for lengthy fine-tuning. It's possible to fine-tune the SAM on your specific task without freezing the image encoder and also utilize the adapters' input.

where to state freezing the image encoder

**Comment by yjdzyr** [comment]
> Hi, thanks for your wonderful work! I have a question that SAM-adapter freezes the image encoder which is described in the paper. But I see that although the freeze code is provided, they are not runned. Whether is it necessary to freeze image encoder. Thanks!

Hi.Where's the code for the freeze encoder.Could you please tell me
