### ISSUE TITLE
Pre-trained model for this project (Adapter)

### ISSUE THREAD

**Issue by moktsuiqin** [tianrun-chen/SAM-Adapter-PyTorch#33]
Hi, could you please provide the pre-trained models for this SAM-Adapter project?

**Comment by tianrun-chen** [comment]
Hello! Please view this link: https://cowtransfer.com/s/da0559afdfc045 click link to check [ best_results.tar ] or access cowtransfer.com and input extract code: y85nd7 to check;

**Comment by moktsuiqin** [comment]
Received the file. Thank you
