### ISSUE TITLE
Has anyone obtained the same results as in the paper? From the code it looks like the Adapter is not added to the training？

### ISSUE THREAD

**Issue by Chen94yue** [tianrun-chen/SAM-Adapter-PyTorch#41]
Adapter is not added to the training or am I misunderstanding the code?

the model is init in:

https://github.com/tianrun-chen/SAM-Adapter-PyTorch/blob/62a83a48b254fdd0cfb71e8be8df87dfa0d5a9d8/train.py#L96-L111

In config file, the code chooses 'sam', and the 'sam' model is defined in 'models/sam.py'.

In the forward of sam:

https://github.com/tianrun-chen/SAM-Adapter-PyTorch/blob/62a83a48b254fdd0cfb71e8be8df87dfa0d5a9d8/models/sam.py#L169-L191

Use "self.image_encoder" to get image embedding, this sub-module is defined in 'ImageEncoderViT', it is implemented in ‘models/mmseg/models/sam/image_encoder.py’. In this file, I just can't find any implemented about adapter, only see one variable that is not being used ‘self.adapter’.

**Comment by pinecho** [comment]
I have the same question, it seems that "self.adaptor = adaptor" was not referenced after the assignment.

**Comment by theneao** [comment]
不就是mlp吗，用了self.mlp，不知道我理解有错不

**Comment by Abhiram-kandiyana** [comment]
yep, and I can't find the code for the High Frquency component using FFT

**Comment by Abhiram-kandiyana** [comment]
@tianrun-chen Can you please help with this. Can you let us know where we can find the code for the adaptor?

**Comment by Abhiram-kandiyana** [comment]
I think it's implemented as prompt-generator in ImageEncoderViT.

**Comment by monstergq** [comment]
In './models/image_encoder.py', the class ImageEncoderViT
![image](https://github.com/tianrun-chen/SAM-Adapter-PyTorch/assets/77041788/1e7ac515-ec66-4074-aa70-c8f887502049)

**Comment by qiuzhongwei-USTB** [comment]
same question

**Comment by tianrun-chen** [comment]
Please Check
models/mmseg/models/sam/image_encoder.py
