### ISSUE TITLE
Pre-trained Models' Links has expired

### ISSUE THREAD

**Issue by hnrna** [tianrun-chen/SAM-Adapter-PyTorch#47]
![image](https://github.com/tianrun-chen/SAM-Adapter-PyTorch/assets/69299447/a7e8e4cf-3043-464a-ae4a-69a2d037b1fd)

**Comment by David-19940718** [comment]
+1, can u share the pretrained model weight again, thank you! @tianrun-chen

**Comment by tianrun-chen** [comment]
Please can you try this link:
https://drive.google.com/file/d/1MMUytUHkAQvMRFNhcDyyDlEx_jWmXBkf/view?usp=sharing

We have also changed the readme to the latest download link. Thx!
