### ISSUE TITLE
train_setr_evp_cod.yaml

### ISSUE THREAD

**Issue by 1289600760** [tianrun-chen/SAM-Adapter-PyTorch#48]
Hello, first of all, thank you very much for your work. I would like to ask about train_setr_evp_cod.yaml, where is this file？I can't find it

![1](https://github.com/tianrun-chen/SAM-Adapter-PyTorch/assets/75231209/f27e0a4e-6edb-4707-83d0-7e8ffc5bf1cb)

**Comment by tianrun-chen** [comment]
Hello! The yaml file is used for defining the datasets and other relavent settings, please change to your own yaml file or change to the dict /demo.yaml we provided for training.
