### ISSUE TITLE
How much memory of GPU is typically consumed when evaluating a model at batch of 1?

### ISSUE THREAD

**Issue by jithf** [tianrun-chen/SAM-Adapter-PyTorch#52]
Memory of my GPU is 24G，“CUDA out of memory” raised when I "python test.py --config config.yaml --model mode_epoch_bets_path". The model is the pretrain model of the author and the bath size was set to 1.

**Comment by tianrun-chen** [comment]
Greetings! As the current application will utilize over 30G of memory for batchsize=1, we suggest considering alternative graphics cards with greater memory capacity.
