### ISSUE TITLE
Video memory problem

### ISSUE THREAD

**Issue by jiaweichaojwc** [tianrun-chen/SAM-Adapter-PyTorch#58]
When I was training, both train and val were normal, but when val saw a surge in video memory, and when I used four A100 video cards for training, I could only train one epoch, and then I was told that the video memory was insufficient. I don't know whether this code made video memory superposition indefinitely instead of releasing, or what was the problem? I don't know if you have encountered this kind of problem can tell me

**Comment by ybk66** [comment]
请问您解决了吗
