### ISSUE TITLE
Demo config may load wrong pretrained weight file?

### ISSUE THREAD

**Issue by DuinoDu** [tianrun-chen/SAM-Adapter-PyTorch#6]
Hi, thanks for awesome work!

I found that given [config yaml use ./pretrained/sam_vit_l_0b3195.pth](https://github.com/tianrun-chen/SAM-Adapter-PyTorch/blob/main/configs/demo.yaml#L45), but sam model actually use `sam_vit_h` config:

https://github.com/tianrun-chen/SAM-Adapter-PyTorch/blob/main/configs/demo.yaml#L86-92

sam config:

https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/build_sam.py#L14-L21

May be a typo?

**Comment by tianrun-chen** [comment]
Thanks for your interests! As we shown in the manuscript, we use the ViT-H version of SAM.
