### ISSUE TITLE
Where are the codes of adapter? 

### ISSUE THREAD

**Issue by ericzw** [tianrun-chen/SAM-Adapter-PyTorch#60]
Where are the codes of adapter?

**Comment by GisRookie** [comment]
i want to know too

**Comment by YinqiCai** [comment]
models/mmseg/models/sam/image_encoder.py

**Comment by tianrun-chen** [comment]
Hello, Please Check 
models/mmseg/models/sam/image_encoder.py

**Comment by zhouxinwen-cpu** [comment]
Is the path differet for sam3-adapter? I found prompt_generator in /models/sam3/model/vitdet.py seems to work as adaper.
