### ISSUE TITLE
When the batch size is set to 2, how much gpu memory is required at least.

### ISSUE THREAD

**Issue by wangqinxuan** [tianrun-chen/SAM-Adapter-PyTorch#70]
My 3090 graphics card has 24G of memory but it’s still not enough. So how much gpu memory is required at least, when the batch size is set to 2.

**Comment by tianrun-chen** [comment]
Hello! We suggest using A100, the application need at least 60Gb of VRAM due to the size of original SAM. But you can try use ViT-L with a 24Gb memory card.
