### ISSUE TITLE
Questions about GPU cards and GPU memory

### ISSUE THREAD

**Issue by guokeqianhg** [tianrun-chen/SAM-Adapter-PyTorch#71]
Hello, thanks for your great work！But I would like to ask how to run from a single GPU, and I wonder to know if it is possible to train with only 8GB GPU memory?

**Comment by tianrun-chen** [comment]
For our default setting, it may require ~60Gb of VRAM, so we suggest using A100 GPU to run the program due to the large VRAM cost of SAM. You can also try to use ViT-H or ViT-B version, which may be lower in accuracy but may be able to run for ~24 Gb of VRAM.
