### ISSUE TITLE
Unable to download the Pretrained model, Please provide the fresh link.

### ISSUE THREAD

**Issue by Adnan-CAS** [tianrun-chen/SAM-Adapter-PyTorch#77]
the link(https://drive.google.com/file/d/1MMUytUHkAQvMRFNhcDyyDlEx_jWmXBkf/view?usp=sharing) to download the the pretrained mode is now working, please provide the new link, Thanks.

**Comment by ajtomar** [comment]
Same issue for me also. The link provided is not working!

**Comment by ZziTaiLeo** [comment]
Same issue for me also. The link provided is not working!

**Comment by cvbird** [comment]
Same issue for me also. The link provided is not working!

**Comment by 77waiwai-Demon** [comment]
The updated link is here: [https://drive.google.com/file/d/13JilJT7dhxwMIgcdtnvdzr08vcbREFlR/view?usp=sharing](https://drive.google.com/file/d/13JilJT7dhxwMIgcdtnvdzr08vcbREFlR/view?usp=sharing)
