### ISSUE TITLE
Does SAM2-Adapter support all SAM2 pre-trained model weights? 

### ISSUE THREAD

**Issue by WangRongsheng** [tianrun-chen/SAM-Adapter-PyTorch#87]
Does SAM2-Adapter support all SAM2 pre-trained model weights? 

The four weights include:
1. sam2_hiera_tiny.pt
2. sam2_hiera_small.pt
3. sam2_hiera_base_plus.pt
4. sam2_hiera_large.pt

**Comment by tianrun-chen** [comment]
Yes, it does support all SAM2 pre-trained model, but it may need minor tweaking on Adapter initialization and configurations. The current implementation is for sam2_hiera_large
