### ISSUE TITLE
dimension error

### ISSUE THREAD

**Issue by Stangerine** [tianrun-chen/SAM-Adapter-PyTorch#90]
/home/a/miniconda3/envs/zzq_sot/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
config loaded.
train dataset: size=37
  inp: shape=(3, 1024, 1024)
  gt: shape=(1, 1024, 1024)
val dataset: size=24
  inp: shape=(3, 1024, 1024)
  gt: shape=(1, 1024, 1024)
  inp_rgb: shape=(3, 1024, 1024)
model: #params=224.5M
model_grad_params: 3943789 
model_total_params: 224512925
model_grad_params: 3943789
train:   0%|                                                                                                                                                    | 0/37 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/train.py", line 257, in <module>
    main(config, save_path)
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/train.py", line 175, in main
    train_loss_G = train(train_loader, model)
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/train.py", line 123, in train
    model.optimize_parameters()
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/models/sam.py", line 395, in optimize_parameters
    self.forward()
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/models/sam.py", line 245, in forward
    low_res_masks, iou_predictions,sam_output_tokens,object_score_logits, = self.mask_decoder(
  File "/home/a/miniconda3/envs/zzq_sot/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/a/miniconda3/envs/zzq_sot/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/models/mmseg/models/sam/mask_decoder.py", line 137, in forward
    masks, iou_pred, mask_tokens_out, object_score_logits = self.predict_masks(
  File "/data/zzq/object_tracking/SAM-Adapter-PyTorch/models/mmseg/models/sam/mask_decoder.py", line 207, in predict_masks
    src = src + dense_prompt_embeddings
RuntimeError: The size of tensor a (128) must match the size of tensor b (256) at non-singleton dimension 1

**Comment by 2023-ZNZX** [comment]
用sam2_hiera_large.pt的模型可以跑通，但是训练完保存下来的模型好像还是跑不通

**Comment by VictorZoo** [comment]
请问，你解决这个问题了吗？我也遇到了。用的也是sam2_hiera_large.pt的模型

**Comment by Stangerine** [comment]
> 请问，你解决这个问题了吗？我也遇到了。用的也是sam2_hiera_large.pt的模型
还没有解决

**Comment by CuckooEcho** [comment]
@Stangerine 我在使用 batch 为 1 的时候也遇到这个错误，通过修改 models/sam.py 下面的代码可以解决，你看和我情况一样不一样

```
def forward(self):
        bs = 1  # 修改 bs 2 to 1
def infer(self, input):
        bs = 1  # 修改 bs 2 为 1
```

**Comment by shidizai-swpu** [comment]
> @Stangerine 我在使用 batch 为 1 的时候也遇到这个错误，通过修改 models/sam.py 下面的代码可以解决，你看和我情况一样不一样
> 
> ```
> def forward(self):
>     bs = 1  # 修改 bs 2 为 1
>     ...
>    feats = [
>         feat.permute(1, 2, 0).view(bs, -1, *feat_size) # 这里 view(2, -1, *feat_size) 修改为 view(bs, -1, *feat_size)   
>            for feat, feat_size in zip(vision_feats[::-1], self._bb_feat_sizes[::-1])
>         ][::-1]
> 
> def infer(self, input):
>     bs = 1 # 修改 bs=1
> 
>     feats = [
>         feat.permute(1, 2, 0).view(bs, -1, *feat_size) # 这里不用改
>         for feat, feat_size in zip(vision_feats[::-1], self._bb_feat_sizes[::-1])
>     ][::-1]
> ```

只能改为2吗？如果我想批次是16或32会报错，怎么办？

**Comment by shidizai-swpu** [comment]
只能改为2吗？如果我想批次是16或32会报错，怎么办？

**Comment by CuckooEcho** [comment]
@shidizai-swpu  你可以将 bs 修改为 batch size 的值，我的显存只够 bs=1 能够运行，所以才改为 1

**Comment by opsliuhao** [comment]
> @shidizai-swpu 你可以将 bs 修改为 batch size 的值，我的显存只够 bs=1 能够运行，所以才改为 1

你好，我根据你的方法改完后可以跑，但是只能跑一个epoch，第二个epoch开始就会卡住，你有这种情况吗？

**Comment by CuckooEcho** [comment]
@opsliuhao 没有遇到这种情况，我是要么就一个 epoch 都不能跑，直接报错，要么是一直能运行。卡住是什么意思？有提示信息吗

**Comment by CuckooEcho** [comment]
@opsliuhao 没有遇到这种情况，我是要么就一个 epoch 都不能跑，直接报错，要么是一直能运行。卡住是什么意思？有提示信息吗

**Comment by tututututurana** [comment]
@CuckooEcho 请问是用sam的代码直接加载sam2_hiera_large.pt吗

**Comment by CuckooEcho** [comment]
@tututututurana 不是吧，他有 sam2 的分支，SAM2-Adapter-for-Segment-Anything-2  , 模型是选 sam2_hiera_large.pt

**Comment by opsliuhao** [comment]
> @opsliuhao 没有遇到这种情况，我是要么就一个 epoch 都不能跑，直接报错，要么是一直能运行。卡住是什么意思？有提示信息吗

没有提示信息，后来通过重启服务器解决了，谢谢。
