### ISSUE TITLE
SAMV2-Adapter Code

### ISSUE THREAD

**Issue by Drchip61** [tianrun-chen/SAM-Adapter-PyTorch#95]
您好，请问您基于SAMV2的adapter代码会公开嘛？

**Comment by tianrun-chen** [comment]
hello, 基于SAM2的adapter代码已经公开，在本项目SAM-2的分支中~
https://github.com/tianrun-chen/SAM-Adapter-PyTorch/tree/SAM2-Adapter-for-Segment-Anything-2
